# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69f2345fbc855ce835c345e14c0fa7f388573b02d3b623890e2c6bbaef2362e228bc886fd3e05251201afb1f39c671172c5ed6ba877009936b201cfa4ad15bd

test:
  secret_key_base: fccba99365be27f9f6c32d028b536d9a1e1511b5cb8759f6cb3bc301df1a41467b53285e502a6748ad8ab70a06023b2881f230e63414c364c093801a36b627bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
